name: "Tests"
on:
  pull_request:
  push:
    branches:
      - original

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, beta, v1.50.0, v1.50.0-beta0]
        source: [action, npm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build Action
        if: matrix.source == 'action'
        run: npm run build
      - name: Install Atom ${{ matrix.version }} with Action
        if: matrix.source == 'action'
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Install Atom ${{ matrix.version }} with NPM
        if: matrix.source == 'npm'
        run: node ./src/action.js ${{ matrix.version }} ${{ secrets.GITHUB_TOKEN }}
      - name: Don't download to repo directory
        run: git add . -N && git diff --name-only --exit-code -- . ':!dist'
      - name: Run Specs
        run: atom --test spec/${{ matrix.version }}

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint ✨
        run: npm run lint

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
